# This role will install ElasticSearch master in group 'elasticsearch' in the environment inventory

- name: add elasticsearch default env vars
  set_fact:
    es_env_vars:
      "node.name": "master-node"
      "cluster.name": "gofka_clsuter"
      "node.master": "true"
      "node.data": "false"
      "network.host": "0.0.0.0"
      "transport.tcp.port": "9300"
      "transport.tcp.compress": "true"
      "bootstrap.memory_lock": "true"
      "ES_JAVA_OPTS": "-Xmx256m -Xms256m"

- name: "(re)start elasticsearch using '{{ es_image }}' "
  vars:
    es_image: "docker.elastic.co/elasticsearch/elasticsearch:6.8.2"
  docker_container:
    name: "es_master"
    image: "{{ es_image }}"
    env: "{{ es_env_vars }}"
    ports:
      - "9300:9300"
    volumes:
      - ./data/master_es:/usr/share/elasticsearch/data:rw
      - ./log/master_es:/usr/share/elasticsearch/log:rw

